server:
  port: 8081
spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  #CONFLICTS WITH HEROKU from local host
        dialect:
          org.hibernate.dialect.MySQL57Dialect
    database: MySQL
    hibernate:
      ddl-auto: none
  #spring.jpa.show-sql=true

#spring.datasource.url = jdbc:mysql://us-cdbr-east-02.cleardb.com/heroku_8089f8997ad0e77?reconnect=true
#spring.datasource.username=b98b87f5bb582a
#spring.datasource.password=8086aae4


  datasource:
    url: "jdbc:mysql://localhost:3306/mushandi_zcatwu?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&failOverReadOnly=false&allowMultiQueries=true&useLegacyDatetimeCode=false&serverTimezone=Africa/Harare"
    username: 'admin'
    password: 'GknotFl@m3s2'

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false



#Using the right database platform is extremely important on Spring Boot 2.0








logging:
  config: classpath:logback-spring.xml
  level:
    ROOT: info
    org.hibernate: error
    org.apache: error
    com.zaxxer.hikari.pool: error
    org.springframework.web: error
    org.springframework.web.filter.CommonsRequestLoggingFilter: error
    zw.co.poscloud.tapswitchpull: info

tempDirectory: tmp/