server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:mysql://localhost:3306/mushandi_zcatwu?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Africa/Harare"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'root'
    password: 'Password@1'


  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: MYSQL
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        enable_lazy_load_no_trans: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

springdoc:
  api-docs:
    path: /api-docs

#Using the right database platform is extremely important on Spring Boot 2.0







logging:
  config: classpath:logback-spring.xml
  level:
    ROOT: info
    org.hibernate: error
    org.apache: error
    com.zaxxer.hikari.pool: error
    org.springframework.web: error
    org.springframework.web.filter.CommonsRequestLoggingFilter: error
    zw.co.poscloud.tapswitchpull: info

tempDirectory: tmp/