server:
  port : 8081

spring:
  #Flames DataSource
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: "jdbc:mysql://167.86.86.168:3306/mushandi_zcatwu_test?zeroDateTimeBehavior=EXCEPTION&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&failOverReadOnly=false&allowMultiQueries=true&useLegacyDatetimeCode=false&serverTimezone=Africa/Harare"
    username: 'admin'
    password: 'GknotFl@m3s2'
    #driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: MYSQL
    #show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        enable_lazy_load_no_trans: true
  application:
    name: mushandi-systemm




  #profiles:
  #active: dev
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false


management:
  endpoints:
    web:
      exposure:
        include: refresh

springdoc:
  api-docs:
    path: /api-docs



  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false



#Using the right database platform is extremely important on Spring Boot 2.0








logging:
  config: classpath:logback-spring.xml
  level:
    ROOT: info
    org.hibernate: error
    org.apache: error
    com.zaxxer.hikari.pool: error
    org.springframework.web: error
    org.springframework.web.filter.CommonsRequestLoggingFilter: error
    zw.co.poscloud.tapswitchpull: info

tempDirectory: tmp/